version: '3.8'

name: volunteerx
services:
  gateway:
    image: gateway
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
      target: development
    command: npm run start:dev
    depends_on:
      - users
      - ping
      - activity
    env_file:
      - ./apps/gateway/.env
    volumes:
      - .:/usr/src/volunteerx
      - /usr/src/volunteerx/node_modules
    ports:
      - '3500:3500'
    expose:
      - 3500
    environment:
      - WATCHPACK_POLLING=true
    restart: always

  users:
    image: users
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
      target: development
    command: npm run start:dev users
    env_file:
      - ./apps/users/.env
    volumes:
      - .:/usr/src/volunteerx
      - /usr/src/volunteerx/node_modules
    ports:
      - '3510:3510'
    expose:
      - '3510'
    environment:
      - WATCHPACK_POLLING=true
    restart: always

  ping:
    image: ping
    build:
      context: .
      dockerfile: ./apps/ping/Dockerfile
      target: development
    command: npm run start:dev ping
    env_file:
      - ./apps/ping/.env
    volumes:
      - .:/usr/src/volunteerx
      - /usr/src/volunteerx/node_modules
    ports:
      - '3520:3520'
    expose:
      - 3520
    depends_on:
      - users
      - rabbitmq
    environment:
      - WATCHPACK_POLLING=true
    restart: always

  activity:
    image: activity
    build:
      context: .
      dockerfile: ./apps/activity/Dockerfile
      target: development
    command: npm run start:dev activity
    env_file:
      - ./apps/activity/.env
    volumes:
      - .:/usr/src/volunteerx
      - /usr/src/volunteerx/node_modules
    ports:
      - '3530:3530'
    expose:
      - 3530
    depends_on:
      - ping
      - users
      - rabbitmq
    environment:
      - WATCHPACK_POLLING=true
    restart: always

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq/
    env_file:
      - ./.env
