scalar ObjectID
scalar Longitude
scalar Latitude
scalar URL
scalar DateTime

type Ping {
  id: String!
  title: String!
  userID: ObjectID!
  longitude: Longitude!
  latitude: Latitude!
  picks: [String!]!
  description: String
  url: URL
  radius: Float
  createdAt: DateTime
  media: [Media]
}

input CreatePingInput {
  userID: ObjectID!
  title: String!
  picks: [String!]!
  longitude: Longitude!
  latitude: Latitude!
  description: String
  url: URL
  radius: Float
}

# type Query {
# }

type Media {
  Key: String!
  type: String!
}

type Mutation {
  createPing(createPingInput: CreatePingInput!): Ping!
  updateMedia(pingID: String!, media: [Media!]!): Ping!
}
