scalar Longitude
scalar Latitude
scalar URL
scalar DateTime

type Media {
  key: String!
  type: String!
}

type Ping @key(fields: "id") {
  id: ID!
  title: String!
  userID: ID!
  user: User
  longitude: Longitude!
  latitude: Latitude!
  picks: [String!]!
  description: String
  url: URL
  radius: Float
  createdAt: DateTime
  media: [Media]
}

extend type User @key(fields: "id") {
  id: ID!
  pings: [Ping]
}

input CreatePingInput {
  userID: ID!
  title: String!
  picks: [String!]!
  longitude: Longitude!
  latitude: Latitude!
  description: String
  url: URL
  radius: Float
}

input UPingInput {
  title: String
  picks: [String!]
  longitude: Longitude
  latitude: Latitude
  description: String
  url: URL
  radius: Float
  media: [MediaInput]
}

input MediaInput {
  key: String!
  type: String!
}

extend type Query {
  getPing(id: ID!): Ping!
}

extend type Mutation {
  createPing(payload: CreatePingInput!): Ping!
  updatePing(id: ID!, payload: UPingInput!): ID!
}
