scalar DateTime
scalar EmailAddress

type Name {
  firstName: String!
  middleName: String
  lastName: String!
}

type User @key(fields: "id") {
  id: ID!
  email: EmailAddress!
  username: String!
  name: Name
  picture: String
  createdAt: DateTime
  picks: [String]
  pings: [Ping]
}

extend type Ping @key(fields: "id") {
  id: ID!
  user: User
}

input CreateUserInput {
  username: String!
  email: EmailAddress!
  firstName: String!
  lastName: String!
  middleName: String
  picture: String
  picks: [String]!
  latitude: Float
  longitude: Float
}

input UpdateUserInput {
  id: ID!
  usename: String
  email: EmailAddress
  firstName: String
  lastName: String
  middleName: String
  picks: [String]
}

extend type Query {
  getUser(id: ID!): User!
  getUserByEmail(email: EmailAddress!): User
  isUsernameAvailable(username: String!): Boolean!
}

extend type Mutation {
  createUser(payload: CreateUserInput!): User!
  updateUser(payload: UpdateUserInput!): User!
  removeUser(id: ID!): User
}

# type Subscription {
#   watchUsernameAvailability(username: String!): Boolean!
# }
