scalar DateTime
scalar Email
scalar ObjectID

enum Role {
  ADMIN
  USER
  ACTIVITY_OWNER
  FORUM_MODERATOR
}

type Name {
  firstName: String!
  middleName: String
  lastName: String!
}

type User {
  id: ObjectID!
  email: String!
  username: String!
  role: Role!
  name: Name
  createdAt: DateTime
  updatedAt: DateTime
}

input CreateUserInput {
  username: String!
  email: Email!
  firstName: String!
  lastName: String!
  middleName: String
  role: Role!
}

input UpdateUserInput {
  id: ObjectID!
  usename: String
  email: String
  firstName: String
  lastName: String
}

type Query {
  users: [User]!
  getUserByID(id: ObjectID!): User
  isUsernameAvailable(username: String!): Boolean!
}

type Mutation {
  createUser(createUserInput: CreateUserInput!): User!
  updateUser(updateUserInput: UpdateUserInput!): User!
  removeUser(id: ObjectID!): User
}

# type Subscription {
#   watchUsernameAvailability(username: String!): Boolean!
# }
